### PR TITLE
resolve #4

### LINKED ISSUE #4: init liquibase

### PR DESCRIPTION
**Pull request by Guseyn**

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by Guseyn** [comment]
@rultor merge

**Comment by Guseyn** [comment]
@rultor merge

**Comment by Guseyn** [comment]
@yegor256 let's try again to merge the pr and see if it builds on rultor side

**Comment by Guseyn** [comment]
@

**Comment by Guseyn** [comment]
I just want to try run travis with docker which contains postgres, so I don't have to use it as external service there.

**Pull request closed without merging**
