### PR TITLE
404 page: resolve #32

### LINKED ISSUE #32: design 404 page

### PR DESCRIPTION
**Pull request by Guseyn**
resolve #32

### CODE REVIEW

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this pull request

**Comment by Guseyn** [comment]
resolve #32

**Comment by 0crat** [comment]
Job [#38](https://github.com/yegor256/codexia/issues/38) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `REV` is banned at [#38](https://github.com/yegor256/codexia/issues/38); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#38` is not assigned, can't get performer

**Comment by 0crat** [comment]
Pull request [#38](https://github.com/yegor256/codexia/issues/38) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
