### PR TITLE
#106 - Increasing daily limits for bots review submission

### PR DESCRIPTION
**Pull request by iakunin**
This PR is for issue: https://github.com/yegor256/codexia/issues/106

What's changed:
* Increasing daily limits for bots review submission up to 300.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@iakunin[/z](https://www.0crat.com/u/iakunin) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by iakunin** [comment]
@yegor256 travis status is not correctly reported to this PR.

This is a link to successful travis-build for this PR: https://travis-ci.org/github/yegor256/codexia/builds/679049933

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#120` is not assigned, can't get performer

**Pull request merged**
