### PR TITLE
#125 Fix /karma page error

### PR DESCRIPTION
**Pull request by fellahi-ali**
This PR fixes the issue #125 by reverting changes introduced in #121 tacky

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@fellahi-ali[/z](https://www.0crat.com/u/fellahi-ali) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#126` is not assigned, can't get performer

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.47`

**Comment by yegor256** [comment]
@fellahi-ali thanks!

**Pull request merged**
