### PR TITLE
resolve #25

### LINKED ISSUE #25: add liquibase migrations to running process with environments

### PR DESCRIPTION
**Pull request by Guseyn**
add liquibase migrations to running process with environments

### CODE REVIEW

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#30](https://github.com/yegor256/codexia/issues/30) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rultor merge

**Comment by Guseyn** [comment]
@yegor256 please merge manually this pr because build command is changed and rultor uses old one.

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#30` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#30](https://github.com/yegor256/codexia/issues/30) is now out of scope

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `REV` is banned at [#30](https://github.com/yegor256/codexia/issues/30); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
