### PR TITLE
#124 fix - Get project by id as JSON

### LINKED ISSUE #124: Unable to get project by id via API
## Steps to reproduce
Send following http-request:
```
GET /p/921.json HTTP/1.1
Host: www.codexia.org
X-Codexia-Token: <bot-token>
```

The same in `curl`:
```
curl --location --request GET 'https://www.codexia.org/p/921.json' \
--header 'X-Codexia-Token: <bot-token>'
```

## Expected behavior
Response contains the same json-object as in `GET /recent.json` response:
```
{
    "id": 921,
    "coordinates": "cdapio/cdap",
    "platform": "github",
    "created": "2020-04-25 20:43:38 +0000",
    "deleted": null,
    "submitter": {
      "id": 8297,
      "login": "codexia-hunter"
    },
    "badges": [
      {
        "id": "902",
        "text": "newbie"
      }
    ]
  }
```

## Actual behavior
Response contains following string:
```
"#<Xia::Project:0x00005644c68dcaa0>"
```

Full http-response:
```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 36
Content-Type: application/json
Date: Sun, 26 Apr 2020 16:18:20 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff

"#<Xia::Project:0x00007f86301bc4f8>"
```

### PR DESCRIPTION
**Pull request by fellahi-ali**
This PR try to fix #124 
I've reverted changes introduced in the commit [sieve and veil 8550ad9](https://github.com/yegor256/codexia/commit/8550ad91eb17964f90e31aac231dd34362a7754e)

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@fellahi-ali[/z](https://www.0crat.com/u/fellahi-ali) this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@fellahi-ali nope, this should be done differently

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#130` is not assigned, can't get performer

**Pull request closed without merging**
