### PR TITLE
#135 don't penalize deleting own projects

### PR DESCRIPTION
**Pull request by fellahi-ali**
In this PR I've tried to fix the problem of getting a penalty for deleting own projects by analogy to [delete own reviews](https://github.com/yegor256/codexia/blob/cedc881c3ab99c19e12c4bfbe36d33785edfc54e/objects/review.rb#L75) implementation

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#139](https://github.com/yegor256/codexia/issues/139); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@fellahi-ali duplicate of #140

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#139` is not assigned, can't get performer

**Comment by 0crat** [comment]
Pull request [#139](https://github.com/yegor256/codexia/issues/139) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
