### PR TITLE
codexia-hunter bot repo link

### PR DESCRIPTION
**Pull request by fellahi-ali**
This PR fix the link to codexia-hunter bot Github repo

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#140](https://github.com/yegor256/codexia/issues/140); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@fellahi-ali can't merge it. Did you try to run the build locally?

**Comment by fellahi-ali** [comment]
> @fellahi-ali can't merge it. Did you try to run the build locally?

@yegor256 No! I didn't, actually I'm not familiar with Ruby, but I just tried to fix the problem by analogy to 'delete own reviews' task, but apparently I've failed and it should be fixed in other way.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#140](https://github.com/yegor256/codexia/issues/140); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#140](https://github.com/yegor256/codexia/issues/140); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Pull request [#140](https://github.com/yegor256/codexia/issues/140) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
